### ISSUE TITLE
Typo in Border Token Output

### ISSUE THREAD

**Issue by david-roeger** [Supernova-Studio/exporter-react#1]
**Describe the bug**
The Output for the border Tokens missspells the "width" Property as "witdh"

**Expected behavior**
The Property is correctly spelled as "width"

**Screenshots**
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/61949735/153441275-1ba71e2d-2037-4860-b5e1-11bcc2701ebf.png">

**Additional context**
The Problem seems to come from [this](https://github.com/Supernova-Studio/exporter-react/blob/master/src/token-renderers/rendered-border.pr#L39) line.

**Comment by JiriTrecak** [comment]
@david-roeger Thank you for reporting! This was now fixed and we have updated the exporter in the platform so all people who use it will have this fixed. Let us know whether it works for you now!

**Comment by david-roeger** [comment]
It worked. Thanks a lot for the quick fix!
